# Build System Configuration
build_tool: uv
dependency_file: pyproject.toml
lock_file: uv.lock

# Development Server
dev_server:
  command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  
# Production Server  
prod_server:
  command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: false

# Docker Build
docker:
  compose_files:
    - docker-compose.yml
    - docker-compose.launchpad.yml
    - docker-compose.supabase.yml
  build_command: "docker-compose build"
  up_command: "docker-compose up -d"
  down_command: "docker-compose down"
  logs_command: "docker-compose logs -f"

# Build Commands
commands:
  install: "uv pip sync uv.lock"
  update_lock: "uv pip compile pyproject.toml -o uv.lock"
  dev: "uvicorn app.main:app --reload"
  build_docker: "docker-compose build"
  start_services: "docker-compose up -d"
  
# Environment Setup
environment:
  python_version: "3.12"
  virtual_env: ".venv"
  env_file: ".env"
  
# Code Quality
quality:
  formatter: ruff
  linter: ruff
  type_checker: pyright
  pre_commit: true